[logger]
level = "error"
messageFormat = "%(message)s"

[runner]
fastReruns = true
enforceSerializableSessionState = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[global]
suppressDeprecationWarnings = true
showWarningOnDirectExecution = false

# Suppress torch-related warnings during module inspection
[theme]
base = "light" 